In [1]:
import numpy as np

foo = np.asarray([[1, 5, 5], [1, 5, 5], [1, 5, 4], [1,4,4], [4,4,4], [4,4,4]])
num_fc_neurons = [3, 3, 3]
print(foo)
print("Getting Unique")
bar = np.unique(foo, axis=0)
first_mismatch = False

# fit Gaussians for each unique non-singleton polytope
for polytope in bar: 
  print(polytope)
  # count the samples that belong exactly to the current polytope_memberships
  total_match = foo==polytope 
  #iterate through all samples in label
  for member in foo:
    weight = 0
    for i, mi in enumerate(member):
      #print(i, mi)
      layer_match = mi == polytope[i]
      if layer_match:
        print(f"mi = {mi}, perfect_match = {layer_match}")
        weight += 1
      else: 
        print(f"mismatch! mi = {mi}, pi = {polytope[i]}")
        hamming_dist = sum([i=="1" for i in np.binary_repr(mi ^ polytope[i])])
        weight += 1 - hamming_dist/num_fc_neurons[i]
        if first_mismatch: break
    print(weight/len(member))

[[1 5 5]
 [1 5 5]
 [1 5 4]
 [1 4 4]
 [4 4 4]
 [4 4 4]]
Getting Unique
[1 4 4]
mi = 1, perfect_match = True
mismatch! mi = 5, pi = 4
mismatch! mi = 5, pi = 4
0.7777777777777778
mi = 1, perfect_match = True
mismatch! mi = 5, pi = 4
mismatch! mi = 5, pi = 4
0.7777777777777778
mi = 1, perfect_match = True
mismatch! mi = 5, pi = 4
mi = 4, perfect_match = True
0.888888888888889
mi = 1, perfect_match = True
mi = 4, perfect_match = True
mi = 4, perfect_match = True
1.0
mismatch! mi = 4, pi = 1
mi = 4, perfect_match = True
mi = 4, perfect_match = True
0.7777777777777778
mismatch! mi = 4, pi = 1
mi = 4, perfect_match = True
mi = 4, perfect_match = True
0.7777777777777778
[1 5 4]
mi = 1, perfect_match = True
mi = 5, perfect_match = True
mismatch! mi = 5, pi = 4
0.888888888888889
mi = 1, perfect_match = True
mi = 5, perfect_match = True
mismatch! mi = 5, pi = 4
0.888888888888889
mi = 1, perfect_match = True
mi = 5, perfect_match = True
mi = 4, perfect_match = True
1.0
mi = 1, perfect_match = True
