In [1]:
import numpy as np

In [2]:
x = np.array([1, 3, 5, 20, 60, 2, 8, 12, 9])

In [3]:
np.where(x > 8)

(array([3, 4, 7, 8]),)

In [4]:
predicted_leaf_ids_across_trees = np.array([4,5,6,6,7,4,5,5,4,6])

In [20]:
for polytope in range(5):
                matched_samples = np.sum(
                    predicted_leaf_ids_across_trees == predicted_leaf_ids_across_trees[polytope],
                    axis=0 #Is =1 in original, but unsure what 2nd dimension contains
                )
                print(predicted_leaf_ids_across_trees)
                print(predicted_leaf_ids_across_trees[polytope])
                print("Value: ", polytope, "\tMatched_Samples",matched_samples)
                
                idx = np.where(
                    matched_samples>0
                )[0]
                
                print("IDX: ",idx)
                
                #scales = matched_samples[idx]/np.max(matched_samples[idx]) 
                #         --> Error because matched_samplesis a scalar

[4 5 6 6 7 4 5 5 4 6]
4
Value:  0 	Matched_Samples 3
IDX:  [0]
[4 5 6 6 7 4 5 5 4 6]
5
Value:  1 	Matched_Samples 3
IDX:  [0]
[4 5 6 6 7 4 5 5 4 6]
6
Value:  2 	Matched_Samples 3
IDX:  [0]
[4 5 6 6 7 4 5 5 4 6]
6
Value:  3 	Matched_Samples 3
IDX:  [0]
[4 5 6 6 7 4 5 5 4 6]
7
Value:  4 	Matched_Samples 1
IDX:  [0]


IndexError: invalid index to scalar variable.

In [14]:
idx

array([0])