In [1]:
# import 
import numpy as np
import random
from proglearn.sims import generate_gaussian_parity
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sc
import sklearn.ensemble
from sklearn import metrics 
import math
from scipy.stats import ttest_ind
from scipy.spatial import distance
import random

In [2]:
# number of samples
n_samples = 100

# generate xor 
X_xor, y_xor = generate_gaussian_parity(n_samples, angle_params=0)

# generate rxor, 45 degrees
X_rxor, y_rxor = generate_gaussian_parity(n_samples, angle_params=np.pi/4)

In [3]:
# we want to pick 70 samples from xor/rxor to train trees so we need to first subset each into arrays with only xor_0/1 and rxor_0/1
X_xor_0 = X_xor[np.where(y_xor == 0)]
X_xor_1 = X_xor[np.where(y_xor == 1)]

X_rxor_0 = X_rxor[np.where(y_rxor == 0)]
X_rxor_1 = X_rxor[np.where(y_rxor == 1)]

# we can concat the first 35 samples from each pair to use to tatal 70 samples for training and 30 for predict proba
X_xor_train = np.concatenate((X_xor_0[0:35], X_xor_1[0:35]))
y_xor_train = np.concatenate((np.zeros(35), np.ones(35)))

# repeat for rxor
X_rxor_train = np.concatenate((X_rxor_0[0:35], X_rxor_1[0:35]))
y_rxor_train = np.concatenate((np.zeros(35), np.ones(35)))

In [4]:
len(X_xor_train), len(X_xor_train)

(70, 70)

In [5]:
# init the rf's
# xor rf
clf_xor = sklearn.ensemble.RandomForestClassifier(n_estimators=10, min_samples_leaf=int(n_samples/7))

# rxor rf
clf_rxor = sklearn.ensemble.RandomForestClassifier(n_estimators=10, min_samples_leaf=int(n_samples/7))

In [6]:
# train rfs
# fit the model using the train data 
clf_xor.fit(X_xor_train, y_xor_train)

# fit rxor model
clf_rxor.fit(X_rxor_train, y_rxor_train)

RandomForestClassifier(min_samples_leaf=14, n_estimators=10)

In [7]:
# concat 30 test samples for both xor and rxor
# xor test
X_xor_test = np.concatenate((X_xor_0[35:], X_xor_1[35:]))

# rxor test 
X_rxor_test = np.concatenate((X_rxor_0[35:], X_rxor_1[35:]))

# predict proba with xor rf
xor_proba_xorRF = clf_xor.predict_proba(X_xor_test)
rxor_proba_xorRF = clf_xor.predict_proba(X_rxor_test)

# predict proba with rxor rf
xor_proba_rxorRF = clf_rxor.predict_proba(X_xor_test)
rxor_proba_rxorRF = clf_rxor.predict_proba(X_rxor_test)

In [8]:
xor_proba_xorRF

array([[0.49827583, 0.50172417],
       [0.57402252, 0.42597748],
       [0.51638587, 0.48361413],
       [0.53822989, 0.46177011],
       [0.41880222, 0.58119778],
       [0.51638587, 0.48361413],
       [0.44074839, 0.55925161],
       [0.49827583, 0.50172417],
       [0.44074839, 0.55925161],
       [0.51638587, 0.48361413],
       [0.53822989, 0.46177011],
       [0.49799203, 0.50200797],
       [0.44074839, 0.55925161],
       [0.44074839, 0.55925161],
       [0.52463677, 0.47536323],
       [0.49827583, 0.50172417],
       [0.57964924, 0.42035076],
       [0.44074839, 0.55925161],
       [0.51638587, 0.48361413],
       [0.53822989, 0.46177011],
       [0.51638587, 0.48361413],
       [0.52193839, 0.47806161],
       [0.52193839, 0.47806161],
       [0.46700012, 0.53299988],
       [0.54388456, 0.45611544],
       [0.54388456, 0.45611544],
       [0.51638587, 0.48361413],
       [0.44035539, 0.55964461],
       [0.47643182, 0.52356818],
       [0.36116557, 0.63883443]])

In [9]:
rxor_proba_xorRF

array([[0.51638587, 0.48361413],
       [0.51638587, 0.48361413],
       [0.53825783, 0.46174217],
       [0.51638587, 0.48361413],
       [0.54936974, 0.45063026],
       [0.51638587, 0.48361413],
       [0.51638587, 0.48361413],
       [0.54936974, 0.45063026],
       [0.51638587, 0.48361413],
       [0.51638587, 0.48361413],
       [0.49141954, 0.50858046],
       [0.41880222, 0.58119778],
       [0.53825783, 0.46174217],
       [0.49799203, 0.50200797],
       [0.36116557, 0.63883443],
       [0.49827583, 0.50172417],
       [0.37361182, 0.62638818],
       [0.53825783, 0.46174217],
       [0.43122052, 0.56877948],
       [0.41880222, 0.58119778],
       [0.55067614, 0.44932386],
       [0.41880222, 0.58119778],
       [0.41880222, 0.58119778],
       [0.53825783, 0.46174217],
       [0.41880222, 0.58119778],
       [0.36116557, 0.63883443],
       [0.51326355, 0.48673645],
       [0.41880222, 0.58119778],
       [0.41880222, 0.58119778],
       [0.51360506, 0.48639494]])

In [10]:
xor_proba_rxorRF 

array([[0.3825032 , 0.6174968 ],
       [0.29817337, 0.70182663],
       [0.87267308, 0.12732692],
       [0.3825032 , 0.6174968 ],
       [0.49178393, 0.50821607],
       [0.87267308, 0.12732692],
       [0.5659098 , 0.4340902 ],
       [0.3825032 , 0.6174968 ],
       [0.5659098 , 0.4340902 ],
       [0.63556064, 0.36443936],
       [0.3825032 , 0.6174968 ],
       [0.29817337, 0.70182663],
       [0.5659098 , 0.4340902 ],
       [0.5659098 , 0.4340902 ],
       [0.29817337, 0.70182663],
       [0.29559844, 0.70440156],
       [0.7050677 , 0.2949323 ],
       [0.5659098 , 0.4340902 ],
       [0.87267308, 0.12732692],
       [0.3825032 , 0.6174968 ],
       [0.82207178, 0.17792822],
       [0.35047142, 0.64952858],
       [0.35047142, 0.64952858],
       [0.63556064, 0.36443936],
       [0.35047142, 0.64952858],
       [0.35047142, 0.64952858],
       [0.63556064, 0.36443936],
       [0.63556064, 0.36443936],
       [0.63556064, 0.36443936],
       [0.63556064, 0.36443936]])

In [11]:
rxor_proba_rxorRF

array([[0.71156064, 0.28843936],
       [0.87267308, 0.12732692],
       [0.27634554, 0.72365446],
       [0.87267308, 0.12732692],
       [0.5659098 , 0.4340902 ],
       [0.63556064, 0.36443936],
       [0.63556064, 0.36443936],
       [0.80302224, 0.19697776],
       [0.71156064, 0.28843936],
       [0.87267308, 0.12732692],
       [0.48468452, 0.51531548],
       [0.29817337, 0.70182663],
       [0.08273499, 0.91726501],
       [0.41440298, 0.58559702],
       [0.63556064, 0.36443936],
       [0.08273499, 0.91726501],
       [0.29817337, 0.70182663],
       [0.08273499, 0.91726501],
       [0.29817337, 0.70182663],
       [0.29817337, 0.70182663],
       [0.08273499, 0.91726501],
       [0.49178393, 0.50821607],
       [0.29817337, 0.70182663],
       [0.08273499, 0.91726501],
       [0.41440298, 0.58559702],
       [0.63556064, 0.36443936],
       [0.08273499, 0.91726501],
       [0.29817337, 0.70182663],
       [0.33523631, 0.66476369],
       [0.35047142, 0.64952858]])

In [18]:
# gets first item in each sublist 
def Extract(lst):
    return list(next(zip(*lst)))